import Footer from '@/Components/Footer/Footer'
import MainNavbar from '@/Components/MainNavbar/MainNavbar'
import Head from 'next/head'

export default function MainLayout({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainNavbar />
            {children}
  <Footer />
        </>
    )
}